version:  '3.3'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/api:/usr/src/apps/api'
    restart: on-failure
    env_file:
      - .env
    user: ${LOCAL_USER}
  api:
    image: nginx:1.19.6-alpine
    container_name: api_server
    restart: on-failure
    volumes:
      - './apps/api/public/:/usr/src/apps/api'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - './apps/frontend:/usr/src/apps/frontend'
    ports:
      - '${FRONTEND_PORT}:8080'
